### PR TITLE
feat(cli): add `db` group alias

### PR DESCRIPTION
**Pull request by cofin**
Add a `db` shorthand alias to the `database` group.  This allows `litestar|alchemy db` or `litestar|alchemy database` to work interchangeably.

### CODE REVIEW

**Comment by sparfenyuk** [comment]
@cofin got an issue after upgrade to 1.8.2 (click==8.3.1):

```
api/routes/api/tests/test_app_routes.py:18: in <module>
    from advanced_alchemy.extensions.litestar.plugins import (
../.venv/lib/python3.12/site-packages/advanced_alchemy/extensions/litestar/__init__.py:5: in <module>
    from advanced_alchemy.extensions.litestar.cli import get_database_migration_plugin
../.venv/lib/python3.12/site-packages/advanced_alchemy/extensions/litestar/cli.py:40: in <module>
    @click.group(cls=LitestarGroup, name="database", aliases=["db"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.12/site-packages/click/decorators.py:248: in decorator
    cmd = cls(name=cmd_name, callback=f, params=params, **attrs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.12/site-packages/litestar/cli/_utils.py:159: in __init__
    super().__init__(name=name, commands=commands, **attrs)  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.12/site-packages/rich_click/rich_command.py:358: in __init__
    Group.__init__(self, *args, **kwargs)
../.venv/lib/python3.12/site-packages/click/core.py:1569: in __init__
    super().__init__(name, **kwargs)
E   TypeError: Command.__init__() got an unexpected keyword argument 'aliases'
```

**Comment by cofin** [comment]
> @cofin got an issue after upgrade to 1.8.2 (click==8.3.1):
> 
> 
> 
> ```
> 
> api/routes/api/tests/test_app_routes.py:18: in <module>
> 
>     from advanced_alchemy.extensions.litestar.plugins import (
> 
> ../.venv/lib/python3.12/site-packages/advanced_alchemy/extensions/litestar/__init__.py:5: in <module>
> 
>     from advanced_alchemy.extensions.litestar.cli import get_database_migration_plugin
> 
> ../.venv/lib/python3.12/site-packages/advanced_alchemy/extensions/litestar/cli.py:40: in <module>
> 
>     @click.group(cls=LitestarGroup, name="database", aliases=["db"])
> 
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> ../.venv/lib/python3.12/site-packages/click/decorators.py:248: in decorator
> 
>     cmd = cls(name=cmd_name, callback=f, params=params, **attrs)
> 
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> ../.venv/lib/python3.12/site-packages/litestar/cli/_utils.py:159: in __init__
> 
>     super().__init__(name=name, commands=commands, **attrs)  # type: ignore[arg-type]
> 
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> ../.venv/lib/python3.12/site-packages/rich_click/rich_command.py:358: in __init__
> 
>     Group.__init__(self, *args, **kwargs)
> 
> ../.venv/lib/python3.12/site-packages/click/core.py:1569: in __init__
> 
>     super().__init__(name, **kwargs)
> 
> E   TypeError: Command.__init__() got an unexpected keyword argument 'aliases'
> 
> ```

Can you tell me if the issue goes away if you install rich-click? 

If so, I'll create a patch to fix this.

**Comment by sparfenyuk** [comment]
> Can you tell me if the issue goes away if you install rich-click?

I have `rich-click==1.8.9` installed.

Upgrade to the latest helped.
